-- 1. Classes Table
CREATE TABLE IF NOT EXISTS public.classes (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    academy_id text, 
    name text,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Classes viewable by everyone" ON public.classes;
CREATE POLICY "Classes viewable by everyone" ON public.classes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Classes insertable by admins" ON public.classes;
CREATE POLICY "Classes insertable by admins" ON public.classes FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Classes deletable by admins" ON public.classes;
CREATE POLICY "Classes deletable by admins" ON public.classes FOR DELETE USING (true);

DROP POLICY IF EXISTS "Classes updatable by admins" ON public.classes;
CREATE POLICY "Classes updatable by admins" ON public.classes FOR UPDATE USING (true);


-- 2. Student Daily Summaries
CREATE TABLE IF NOT EXISTS public.student_daily_summaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid,
    date text,
    tests jsonb DEFAULT '[]'::jsonb,
    created_at timestamptz DEFAULT now(),
    UNIQUE(user_id, date)
);
ALTER TABLE public.student_daily_summaries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Summaries viewable by everyone" ON public.student_daily_summaries;
CREATE POLICY "Summaries viewable by everyone" ON public.student_daily_summaries FOR SELECT USING (true);

DROP POLICY IF EXISTS "Summaries insertable by everyone" ON public.student_daily_summaries;
CREATE POLICY "Summaries insertable by everyone" ON public.student_daily_summaries FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Summaries updatable by everyone" ON public.student_daily_summaries;
CREATE POLICY "Summaries updatable by everyone" ON public.student_daily_summaries FOR UPDATE USING (true);


-- 3. Chats Table
CREATE TABLE IF NOT EXISTS public.chats (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  student_id uuid,
  student_name text,
  teacher_id uuid,
  teacher_name text,
  academy_id text,
  last_message text,
  updated_at timestamptz DEFAULT now(),
  unread_count jsonb DEFAULT '{}'::jsonb
);
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chats viewable by everyone" ON public.chats;
CREATE POLICY "Chats viewable by everyone" ON public.chats FOR SELECT USING (true);

DROP POLICY IF EXISTS "Chats insertable by everyone" ON public.chats;
CREATE POLICY "Chats insertable by everyone" ON public.chats FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Chats updatable by everyone" ON public.chats;
CREATE POLICY "Chats updatable by everyone" ON public.chats FOR UPDATE USING (true);


-- 4. Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  chat_id uuid REFERENCES public.chats(id) ON DELETE CASCADE,
  sender_id uuid,
  sender_name text,
  text text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Messages viewable by everyone" ON public.messages;
CREATE POLICY "Messages viewable by everyone" ON public.messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Messages insertable by everyone" ON public.messages;
CREATE POLICY "Messages insertable by everyone" ON public.messages FOR INSERT WITH CHECK (true);


-- 5. Battles Table
CREATE TABLE IF NOT EXISTS public.battles (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  name text,
  password text,
  difficulty text DEFAULT 'normal',
  selected_book text,
  host_id uuid,
  host_name text,
  status text DEFAULT 'waiting',
  created_at timestamptz DEFAULT now(),
  players jsonb DEFAULT '{}'::jsonb,
  player_count int DEFAULT 1,
  max_players int DEFAULT 2,
  game_type text DEFAULT 'battle'
);
ALTER TABLE public.battles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Battles viewable by everyone" ON public.battles;
CREATE POLICY "Battles viewable by everyone" ON public.battles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Battles insertable by everyone" ON public.battles;
CREATE POLICY "Battles insertable by everyone" ON public.battles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Battles updatable by everyone" ON public.battles;
CREATE POLICY "Battles updatable by everyone" ON public.battles FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Battles deletable by everyone" ON public.battles;
CREATE POLICY "Battles deletable by everyone" ON public.battles FOR DELETE USING (true);
