-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Users table (maps to Firestore 'users' collection)
-- Using Supabase Auth 'users' table is standard, but we need a public profile table.
-- We will create a 'profiles' table that references auth.users, OR just a 'users' table if we don't strictly bind to auth.users yet (but we should).
-- For this migration, to keep it simple and consistent with Firestore 'users' collection which holds role/status data:
-- We will create a public.users table. Ideally, this should be linked to auth.users via triggers.

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade, -- Maps to Firebase UID (we will need to sync this)
  email text,
  username text,
  name text,
  role text default 'student', -- 'student', 'admin', 'super_admin'
  academy_id text,
  status text default 'active', -- 'active', 'suspended'
  created_at timestamptz default now(),
  status_updated_at timestamptz
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;

-- Policies (Simple setup for now)
create policy "Public users are viewable by everyone" on public.users for select using (true);
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);

-- 2. Academies table (maps to Firestore 'academies' collection)
create table public.academies (
  id text primary key, -- Keeping text ID to match current manual IDs if any, or uuid
  name text,
  active_students int default 0,
  suspended_students int default 0,
  created_at timestamptz default now()
);

alter table public.academies enable row level security;
create policy "Academies are viewable by everyone" on public.academies for select using (true);

-- 3. Student Status Logs (maps to Firestore 'student_status_logs')
create table public.student_status_logs (
  id bigint generated by default as identity primary key,
  student_id uuid references public.users(id),
  academy_id text references public.academies(id),
  status text,
  changed_at timestamptz default now(),
  changed_by uuid -- references local user id
);

alter table public.student_status_logs enable row level security;
create policy "Logs viewable by admins" on public.student_status_logs for select using (true); -- Refine later

-- 4. Franchise Settings (maps to Firestore 'franchise_settings')
create table public.franchise_settings (
  academy_id text primary key references public.academies(id),
  billing_type text default 'per_student',
  price_per_student int default 0,
  flat_rate_amount int default 0,
  updated_at timestamptz default now()
);

alter table public.franchise_settings enable row level security;
create policy "Settings viewable by admins" on public.franchise_settings for select using (true);

-- 5. Books (maps to Firestore 'books' collection)
create table public.books (
  id text primary key, -- academyId_bookName
  academy_id text references public.academies(id),
  name text,
  total_words int default 0,
  updated_at timestamptz default now()
);

alter table public.books enable row level security;
create policy "Books viewable by everyone" on public.books for select using (true);

-- 6. Words (maps to Firestore 'words' collection)
create table public.words (
  id text primary key, -- Original Firestore ID
  academy_id text references public.academies(id),
  book_name text,
  word text,
  meaning text,
  -- Add other fields as per word data structure
  created_at timestamptz default now()
);

alter table public.words enable row level security;
create policy "Words viewable by everyone" on public.words for select using (true);

-- Functions to handle new user signup automatically (optional but recommended)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for auth
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
